# Generated by Django 6.0.7 on 2026-07-11 11:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaystackTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('purpose', models.CharField(db_index=True, help_text="Caller-chosen tag, e.g. 'property_report'. Used only for signal-receiver filtering.", max_length=50)),
                ('external_reference', models.CharField(db_index=True, help_text='Opaque id from the calling app (e.g. a property_intel report id). Never validated or looked up here.', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in the major currency unit (e.g. KES, not cents).', max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], db_index=True, default='pending', max_length=20)),
                ('authorization_url', models.URLField(blank=True)),
                ('access_code', models.CharField(blank=True, max_length=100)),
                ('paystack_transaction_id', models.CharField(blank=True, help_text="Paystack's own numeric transaction id (data.id), once known.", max_length=50)),
                ('channel', models.CharField(blank=True, help_text="e.g. 'mobile_money', 'card' — from Paystack's response.", max_length=30)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('callback_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['purpose', 'external_reference'], name='payments_pa_purpose_a1b102_idx'), models.Index(fields=['status', 'created_at'], name='payments_pa_status_6d9a17_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaystackWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, help_text="Paystack's `event` field, e.g. 'charge.success'.", max_length=100)),
                ('reference', models.CharField(db_index=True, help_text='The `data.reference` field from the payload.', max_length=100)),
                ('signature_valid', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False, help_text='True once this event actually caused a state transition (vs. being a duplicate/no-op/invalid delivery).')),
                ('processing_note', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('paystack_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='payments.paystacktransaction')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['reference', 'event_type'], name='payments_pa_referen_bd726c_idx')],
                'constraints': [models.UniqueConstraint(fields=('event_type', 'reference'), name='unique_event_per_reference')],
            },
        ),
    ]
