# Generated by Django 4.2.13 on 2026-07-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystacktransaction',
            name='authorization_details',
            field=models.JSONField(blank=True, default=dict, help_text="Raw data.authorization object from Paystack's verify/webhook response — bin/last4 for cards, provider-specific fields for mobile money. Stored as-is; interpreted downstream by whichever app needs it (e.g. property_intel's anti-abuse hashing), never parsed here."),
        ),
    ]
