# Generated by Django 4.2.13 on 2026-07-12 07:11

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersignup_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, unique=True, validators=[users.models.validate_phone_field]),
        ),
    ]
