# Generated by Django 4.2.13 on 2026-06-21 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('service', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('page_url', models.URLField(blank=True, help_text='Which page the form was submitted from', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('welcome_email_sent', models.BooleanField(default=False)),
                ('admin_notified', models.BooleanField(default=False)),
                ('synced_to_brevo', models.BooleanField(default=False)),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='visitors.visitor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
