# Generated by Django 6.0.7 on 2026-07-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_expand_application_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationentry',
            name='auto_extracted',
        ),
        migrations.RemoveField(
            model_name='employmententry',
            name='auto_extracted',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='parsed_resume',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume_parse_failed',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume_raw_text',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume_storage_path',
            field=models.CharField(blank=True, help_text="Path in the private Supabase 'resumes' bucket. Use storage.get_signed_url() to generate a temporary link — never store a public URL here.", max_length=500),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume_upload_failed',
            field=models.BooleanField(default=False, help_text='True if storage upload failed at submission time — application still saved.'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume_filename',
            field=models.CharField(blank=True, help_text='Original filename, for display.', max_length=255),
        ),
    ]
