# Generated by Django 4.2.13 on 2026-07-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_educationentry_auto_extracted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume_storage_path',
            field=models.CharField(blank=True, help_text='Deprecated — no longer used. Resumes are emailed directly, never stored. to generate a temporary link — never store a public URL here.', max_length=500),
        ),
    ]
