# Generated by Django 4.2.13 on 2026-07-16 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=150)),
                ('client_email', models.EmailField(db_index=True, max_length=254)),
                ('client_company', models.CharField(blank=True, max_length=150)),
                ('title', models.CharField(max_length=255)),
                ('scope_of_work', models.TextField(blank=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('negotiating', 'Negotiating'), ('signed', 'Signed'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('access_token_hash', models.CharField(blank=True, max_length=64)),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('esign_method', models.CharField(choices=[('self_built', 'Self-built'), ('third_party', 'Third-party')], default='self_built', max_length=20)),
                ('esign_provider', models.CharField(blank=True, help_text="Set once a third-party e-sign provider is wired in, e.g. 'docusign'.", max_length=50)),
                ('esign_envelope_id', models.CharField(blank=True, max_length=100)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_by_name', models.CharField(blank=True, max_length=150)),
                ('signed_by_email', models.EmailField(blank=True, max_length=254)),
                ('signed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signed_user_agent', models.TextField(blank=True)),
                ('signed_content_hash', models.CharField(blank=True, help_text='SHA-256 of title+scope+value at the moment of signing — if the terms are ever edited afterward, this stops matching, which is the tamper signal.', max_length=64)),
                ('contract_document', models.FileField(blank=True, help_text='Final signed PDF — uploaded manually, or by a future e-sign integration.', null=True, upload_to='contracts/signed/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_contracts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_created', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, help_text='The inquiry this deal originated from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('order', models.PositiveIntegerField(default=0)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('waived', 'Waived'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('paystack_reference', models.CharField(blank=True, db_index=True, help_text='Set once a PaystackTransaction has been initialized for this milestone.', max_length=100)),
                ('invoiced_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='contracts.contract')),
            ],
            options={
                'ordering': ['contract', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('admin', 'Admin'), ('client', 'Client')], db_index=True, max_length=10)),
                ('sender_name', models.CharField(blank=True, help_text='Display name. Always set for token-link clients (no account to pull a name from).', max_length=150)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_by_admin_at', models.DateTimeField(blank=True, null=True)),
                ('read_by_client_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='contracts.contract')),
                ('sender_user', models.ForeignKey(blank=True, help_text='Set for an authenticated admin, or a client with a linked account. Blank for a client messaging via an access-token link — sender_name covers that case.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('scope_of_work', models.TextField(blank=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('note', models.TextField(blank=True, help_text='What changed and why — shown to the client in the thread.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='contracts.contract')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['contract', 'version_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='contractrevision',
            constraint=models.UniqueConstraint(fields=('contract', 'version_number'), name='unique_revision_per_contract'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['client_email', 'status'], name='contracts_c_client__c00889_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status', 'created_at'], name='contracts_c_status_efee21_idx'),
        ),
    ]
