# Generated by Django 4.2.13 on 2026-06-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColdProspectProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Cold Prospect',
                'verbose_name_plural': 'Cold Prospects',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('visitors.visitor',),
        ),
        migrations.AddField(
            model_name='visitor',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='company_domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='visitor',
            name='company_industry',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='visitor',
            name='company_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='visitor',
            name='company_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='visitor',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='country_code',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='visitor',
            name='is_enriched',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='visitor',
            name='isp',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='visitor',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
