# Generated by Django 4.2.13 on 2026-07-11 10:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.CharField(choices=[('geocoding', 'Geocoding API'), ('maps_static', 'Maps Static API'), ('street_view_static', 'Street View Static API'), ('street_view_metadata', 'Street View Metadata (free — checks availability before billing for the image)'), ('places_nearby', 'Places API (New) — Nearby Search'), ('routes', 'Routes API'), ('air_quality', 'Air Quality API')], db_index=True, max_length=30)),
                ('request_params', models.JSONField(blank=True, default=dict)),
                ('response_status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('succeeded', models.BooleanField(default=False)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=5, default=0, help_text="Estimated cost of THIS call based on the SKU's published price — not billed truth, Google's own billing dashboard is the source of truth for actual spend.", max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_is_disposable', models.BooleanField(default=False, help_text='Flagged at signup if the email domain matches a known disposable/temp-mail provider list.')),
                ('signup_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('payment_method_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 of the M-Pesa number or card fingerprint from the first confirmed Paystack payment.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_active_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_hash', models.CharField(db_index=True, max_length=100, unique=True)),
                ('free_reports_remaining', models.PositiveSmallIntegerField(default=4)),
                ('free_reports_used_total', models.PositiveIntegerField(default=0)),
                ('first_seen_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('known_ips', models.JSONField(blank=True, default=list, help_text='All IPs ever seen with this fingerprint, most recent last.')),
                ('linked_emails', models.JSONField(blank=True, default=list, help_text='All emails ever associated with this fingerprint — a growing list here is itself a fraud signal.')),
                ('is_blocked', models.BooleanField(default=False, help_text='Manually blocked after fraud review — hard stop regardless of remaining count.')),
                ('block_reason', models.TextField(blank=True)),
                ('is_datacenter_ip', models.BooleanField(default=False, help_text='True if first_seen_ip resolved to a known VPN/proxy/datacenter ASN rather than a residential/mobile ISP.')),
                ('ip_asn_name', models.CharField(blank=True, help_text="ISP/ASN name for first_seen_ip, e.g. 'Safaricom PLC' vs 'DigitalOcean'.", max_length=255)),
                ('suspicion_score', models.PositiveSmallIntegerField(default=0, help_text='Latest computed fraud score (see fraud.py). Not cumulative — recalculated each time it matters.')),
                ('requires_otp_verification', models.BooleanField(default=False, help_text='Set True when suspicion_score crosses the OTP threshold — free report withheld until phone OTP confirms a real number.')),
                ('otp_verified_phone', models.CharField(blank=True, max_length=20)),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='FraudReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('score_computed', 'Suspicion score computed'), ('otp_required', 'OTP verification required'), ('otp_verified', 'OTP verification completed'), ('held_for_review', 'Held for manual review'), ('manually_blocked', 'Manually blocked'), ('manually_unblocked', 'Manually unblocked')], max_length=30)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('actor', models.CharField(blank=True, help_text='Admin username for manual actions (block/unblock); blank for automated scoring events.', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geohash', models.CharField(db_index=True, help_text='Geohash at 7-char precision (~150m cell).', max_length=12, unique=True)),
                ('center_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('center_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('formatted_address', models.CharField(blank=True, max_length=500)),
                ('geocode_raw_response', models.JSONField(blank=True, default=dict, help_text='Full Geocoding API response, kept for reprocessing without a re-call.')),
                ('satellite_image_url', models.URLField(blank=True, help_text='Maps Static API — top-down satellite/map view.')),
                ('satellite_image_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('street_view_available', models.BooleanField(default=False, help_text='Whether Google has street-level imagery for this cell at all.')),
                ('street_view_image_url', models.URLField(blank=True)),
                ('street_view_pano_id', models.CharField(blank=True, help_text="Google's panorama ID — lets us re-derive the image URL without re-querying metadata.", max_length=100)),
                ('street_view_heading', models.FloatField(blank=True, help_text='Camera heading used, for reproducing the same framing later.', null=True)),
                ('street_view_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('nearby_schools', models.JSONField(blank=True, default=list)),
                ('nearby_hospitals', models.JSONField(blank=True, default=list)),
                ('nearby_banks', models.JSONField(blank=True, default=list)),
                ('nearby_petrol_stations', models.JSONField(blank=True, default=list)),
                ('nearby_shopping', models.JSONField(blank=True, default=list)),
                ('amenities_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('air_quality_raw_response', models.JSONField(blank=True, default=dict)),
                ('air_quality_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('air_quality_category', models.CharField(blank=True, max_length=100)),
                ('air_quality_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('travel_times', models.JSONField(blank=True, default=dict)),
                ('travel_times_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('first_queried_at', models.DateTimeField(auto_now_add=True)),
                ('last_refreshed_at', models.DateTimeField(auto_now=True)),
                ('times_reused', models.PositiveIntegerField(default=0, help_text='Incremented every time a NEW pin lands in this cell without needing fresh API calls. Your caching ROI, made visible.')),
            ],
            options={
                'ordering': ['-last_refreshed_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyPin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_input', models.TextField(help_text='Exactly what the broker pasted, before any parsing.')),
                ('input_type', models.CharField(choices=[('coordinates', 'Raw coordinates'), ('google_maps_link', 'Google Maps link'), ('google_maps_short_link', 'Google Maps short link'), ('whatsapp_location', 'WhatsApp shared location'), ('unknown', 'Unrecognized format')], default='unknown', max_length=30)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('was_cache_hit', models.BooleanField(default=False, help_text='True if location_cell already existed and had complete data when this pin was submitted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pins', to='property_intel.broker')),
                ('location_cell', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pins', to='property_intel.locationcell')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('awaiting_payment', 'Awaiting payment'), ('awaiting_review', 'Awaiting manual fraud review'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('pdf_storage_path', models.CharField(blank=True, max_length=500)),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('investment_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('accessibility_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ai_summary_text', models.TextField(blank=True)),
                ('is_free_tier', models.BooleanField(default=True, help_text="Consumed from the device's free report allowance.")),
                ('price_charged_kes', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paystack_reference', models.CharField(blank=True, db_index=True, help_text='Paystack transaction reference — set when payment initializes, confirmed via webhook.', max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='property_intel.propertypin')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('code_hash', models.CharField(max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_fingerprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_attempts', to='property_intel.devicefingerprint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='locationcell',
            index=models.Index(fields=['geohash'], name='property_in_geohash_b049b1_idx'),
        ),
        migrations.AddField(
            model_name='fraudreviewlog',
            name='device_fingerprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_logs', to='property_intel.devicefingerprint'),
        ),
        migrations.AddField(
            model_name='broker',
            name='device_fingerprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brokers', to='property_intel.devicefingerprint'),
        ),
        migrations.AddField(
            model_name='apicalllog',
            name='location_cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_calls', to='property_intel.locationcell'),
        ),
        migrations.AddIndex(
            model_name='propertypin',
            index=models.Index(fields=['latitude', 'longitude'], name='property_in_latitud_4271c5_idx'),
        ),
        migrations.AddIndex(
            model_name='propertypin',
            index=models.Index(fields=['location_cell', 'created_at'], name='pin_cell_velocity_idx'),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['device_fingerprint', 'created_at'], name='property_in_device__82a267_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudreviewlog',
            index=models.Index(fields=['device_fingerprint', 'created_at'], name='property_in_device__240252_idx'),
        ),
        migrations.AddIndex(
            model_name='apicalllog',
            index=models.Index(fields=['api', 'created_at'], name='property_in_api_da89f4_idx'),
        ),
    ]
