# Generated by Django 4.2.13 on 2026-07-12 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property_intel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devicefingerprint',
            name='free_reports_remaining',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
