# Generated by Django 4.2.13 on 2026-07-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_intel', '0002_broker_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationcell',
            name='nearby_restaurants',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='nearby_supermarkets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='nearby_universities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
