# Generated by Django 4.2.13 on 2026-07-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_intel', '0003_locationcell_nearby_restaurants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationcell',
            name='elevation_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='elevation_meters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='nearby_gated_communities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='nearby_student_housing',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='nearest_road_distance_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='on_paved_road',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='road_context_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apicalllog',
            name='api',
            field=models.CharField(choices=[('geocoding', 'Geocoding API'), ('maps_static', 'Maps Static API'), ('street_view_static', 'Street View Static API'), ('street_view_metadata', 'Street View Metadata (free — checks availability before billing for the image)'), ('places_nearby', 'Places API (New) — Nearby Search'), ('routes', 'Routes API'), ('air_quality', 'Air Quality API'), ('elevation', 'Elevation API'), ('roads', 'Roads API'), ('places_text', 'Places API (New) — Text Search')], db_index=True, max_length=30),
        ),
    ]
