# Generated by Django 4.2.13 on 2026-07-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_intel', '0004_locationcell_elevation_fetched_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicefingerprint',
            name='free_reports_remaining',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
