# Generated by Django 4.2.13 on 2026-07-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_intel', '0005_alter_devicefingerprint_free_reports_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationcell',
            name='air_quality_forecast_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='air_quality_forecast_raw',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='air_quality_good_days_streak',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='air_quality_history_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='air_quality_history_raw',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='elevation_grid',
            field=models.JSONField(blank=True, default=list, help_text='5-point sample (center + N/E/S/W ~150m) used to derive slope.'),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='elevation_slope_range_m',
            field=models.FloatField(blank=True, help_text='max-min elevation across the sample grid -- a real slope signal, not a single-point guess.', null=True),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='nearby_ev_charging',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='nearby_fire_stations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='nearby_parks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='nearby_pharmacies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='nearby_police_stations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='nearby_transit_stops',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='nearest_towns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='nearest_towns_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
