# Generated by Django 4.2.13 on 2026-07-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_intel', '0006_locationcell_air_quality_forecast_fetched_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertypin',
            name='input_type',
            field=models.CharField(choices=[('coordinates', 'Raw coordinates'), ('google_maps_link', 'Google Maps link'), ('google_maps_short_link', 'Google Maps short link'), ('whatsapp_location', 'WhatsApp shared location'), ('plus_code', 'Google Plus Code'), ('unknown', 'Unrecognized format')], default='unknown', max_length=30),
        ),
    ]
