# Generated by Django 4.2.13 on 2026-07-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_intel', '0007_alter_propertypin_input_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationcell',
            name='nearest_road_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='propertyreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_payment', 'Awaiting payment'), ('awaiting_review', 'Awaiting manual fraud review'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
