# Generated by Django 4.2.13 on 2026-07-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_intel', '0008_locationcell_nearest_road_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationcell',
            name='major_road_context_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='nearest_major_road_distance_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='nearest_major_road_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
