# Generated by Django 4.2.13 on 2026-07-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_intel', '0009_locationcell_major_road_context_fetched_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyreport',
            name='wallet_applied_kes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Partial wallet balance earmarked toward this report's price at checkout time (e.g. KES 36 of a KES 199 report). Only actually debited from the wallet once the Paystack remainder is confirmed paid -- see property_intel/signals.py.", max_digits=8, null=True),
        ),
    ]
