# Generated by Django 4.2.13 on 2026-07-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_intel', '0010_propertyreport_wallet_applied_kes'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationcell',
            name='nearby_roads',
            field=models.JSONField(blank=True, default=list, help_text="Up to 3 nearest named roads, nearest first: [{'name':.., 'distance_m':..}, ...]. Not filtered by road classification."),
        ),
    ]
