# Generated by Django 4.2.13 on 2026-07-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_intel', '0011_locationcell_nearby_roads'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationcell',
            name='avg_annual_rainfall_mm',
            field=models.FloatField(blank=True, help_text="Approximate average annual rainfall in mm, derived from NASA POWER's 30-year PRECTOTCORR climatology (ANN daily average x 365).", null=True),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='avg_annual_temp_c',
            field=models.FloatField(blank=True, help_text='Average annual air temperature (deg C), NASA POWER T2M climatology, ANN value.', null=True),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='climate_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='climate_raw_response',
            field=models.JSONField(blank=True, default=dict, help_text='Full NASA POWER climatology/point response, kept for reprocessing without a re-call.'),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='soil_clay_pct',
            field=models.FloatField(blank=True, help_text='Topsoil clay content, mapped value / 10, in percent.', null=True),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='soil_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='soil_nitrogen_g_per_kg',
            field=models.FloatField(blank=True, help_text='Topsoil total nitrogen, mapped value / 100, in g/kg.', null=True),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='soil_organic_carbon_g_per_kg',
            field=models.FloatField(blank=True, help_text='Topsoil organic carbon (soc), mapped value / 10, in g/kg.', null=True),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='soil_ph',
            field=models.FloatField(blank=True, help_text='Topsoil (0-5cm) pH in water (phh2o), mapped value / 10.', null=True),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='soil_raw_response',
            field=models.JSONField(blank=True, default=dict, help_text='Full ISRIC SoilGrids properties/query response, kept for reprocessing without a re-call.'),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='soil_sand_pct',
            field=models.FloatField(blank=True, help_text='Topsoil sand content, mapped value / 10, in percent.', null=True),
        ),
        migrations.AddField(
            model_name='locationcell',
            name='soil_silt_pct',
            field=models.FloatField(blank=True, help_text='Topsoil silt content, mapped value / 10, in percent.', null=True),
        ),
    ]
